// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDScORA2IymJbT5sYaxej_RmDM_OFqRurw',
    appId: '1:436134775966:web:e68e3f0c10a9e2086d3f8f',
    messagingSenderId: '436134775966',
    projectId: 'unispaces-2ea9a',
    authDomain: 'unispaces-2ea9a.firebaseapp.com',
    storageBucket: 'unispaces-2ea9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkyD9QBU6KwgcSxQNPkrta8OifGTEHgg',
    appId: '1:436134775966:android:0c68f2312252de316d3f8f',
    messagingSenderId: '436134775966',
    projectId: 'unispaces-2ea9a',
    storageBucket: 'unispaces-2ea9a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDScORA2IymJbT5sYaxej_RmDM_OFqRurw',
    appId: '1:436134775966:web:3f7b08c54f6de8866d3f8f',
    messagingSenderId: '436134775966',
    projectId: 'unispaces-2ea9a',
    authDomain: 'unispaces-2ea9a.firebaseapp.com',
    storageBucket: 'unispaces-2ea9a.firebasestorage.app',
  );
}
